# Generated by Django 3.1.7 on 2021-03-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.IntegerField()),
            ],
        ),
    ]
